###-------------------------------------------------------------------------------------###
###-------------------------------------------------------------------------------------###
### Wrapper functions for visual EDA of missingness in a meta-analysis.
###-------------------------------------------------------------------------------------###
###-------------------------------------------------------------------------------------###

###---Dependencies
library(tidyverse)

###---Functions

###-----------------------------------------------------------------------------------###
#' # Function to plot distribution of ES or SE colored by whether a covariate is missing
#' @name gg_es_covariate_miss
#' @param shadow: shadow object of a tibble generated by nanair
#' @param es_col: string indicating the effect size column name
#' @param covariate: string indicating the covariate column name
#' @param adjust: numeric indicating the kernel bandwith adjustment for
#'                density plots.
#' @return plot of the density of the effect sizes colored according to if
#'         the covariate is missing or not
#' @note The function will work if you specify any es_col that corresponds to 
#'       a continuous variable in the tibble.
#' ###--------------------------------------------------------------------------------###
gg_es_covariate_miss <- function(shadow, es_col, covariate, adjust = 1){
  
  # Make sure we get the missingness indicator
  cov_na <- paste0(covariate, "_NA")
  
  # Construct plot
  p_es <- ggplot(shadow) +
    aes_string(x = es_col,
               colour = cov_na) + 
    stat_density(geom = "line", # Use stat_density to avoid x-axis lines
                 position = "identity", 
                 adjust = adjust, # adjust smoothing bandwidth
                 size = 1)
  
  # Return plot
  return(p_es)
}


###------------------------------------------------------------------------------------------###   
# Funciton to plot ES and SE plots in a grid
#' @name gg_esse_covariate_miss
#' @param shadow: shadow object of a tibble generated by nanair
#' @param es_col: string indicating the effect size column name
#' @param se_col: string indicating the standard error of the effect size column name
#' @param covariate: string indicating the covariate column name
#' @param adjust: list of numerics indicating the kernel bandwith adjustment for
#'                density plots. Order of list gives smoothing for plots on:
#'                c(effect size, standard error)
#' @param colors: list of colors (length 2)
#' @param ymax: numeric max density to display in plots
#' @param label: label for the color legend. Defaults to covariate column name.
#' @return side-by-side plots of the density of the effect sizes and their standard errors 
#'         colored according to if the covariate is missing or not
#' ###---------------------------------------------------------------------------------------###   
gg_esse_covariate_miss <- function(shadow, es_col, se_col, covariate, adjust = c(1, 1), 
                                   colors = c("#56B4E9", "#E69F00"), ymax = NULL, label = NULL){
  
  # Sterilize input
  if(length(adjust) == 1){ adjust <- rep(adjust, 2) }
  if(is.null(label)){ label <- covariate }
  if(!is.null(ymax)){ ymax <- ylim(0, ymax) }
  
  ## ES plot
  p_es <- gg_es_covariate_miss(shadow, es_col, covariate, adjust[1]) + 
    scale_color_manual(label, values = colors, labels = c("Not Missing", "Missing")) +
    ymax + 
    labs(x = "Effect Size", y = "Density") +
    theme_bw() + 
    guides(color = guide_legend(override.aes = list(size = 1.2)))
  
  ## SE plot
  p_se <- gg_es_covariate_miss(shadow, se_col, covariate, adjust[2]) + 
    scale_color_manual(label, values = colors, labels = c("Not Missing", "Missing")) +
    ymax + 
    labs(x = "Standard Error of Effect Size") +
    theme_bw()
  
  # Extract legend
  legend <- get_legend(p_es + theme(legend.position = "bottom"))
  
  # Arrange plots in a grid
  prow <- plot_grid(p_es + 
                      theme(legend.position = "none"), 
                    #
                    p_se + 
                      theme(legend.position = "none") + 
                      labs(y = ""), # second y-label is superfluous
                    nrow=1)
  
  # Create grid plot
  out <- plot_grid(prow, legend, ncol=1, rel_heights=c(1, .08)) 
  
  # Return grid plot
  return(out)
}

# # Example
# gg_esse_covariate_miss(adt_shadow,
#                        es_col = "es_g", 
#                        se_col = "se_g", 
#                        covariate = "g1hrsperweek", 
#                        adjust = c(1.3, 1.2), # Adjust smoothing for ES and SE densitites
#                        label = "Group 1 Hrs Per Week")



###-------------------------------------------------------------------------------###  
# Funciton to make forest plot 
#' @name gg_forest_covariate_miss
#' @param shadow: shadow object of a tibble generated by nanair
#' @param es_col: string indicating the effect size column name
#' @param se_col: string indicating the standard error of the effect size column name
#' @param covariate: string indicating the covariate column name
#' @param colors: list of colors (length 2)
#' @param label: label for the color legend. Defaults to covariate column name.
#' @return forest plot of effect sizes colored by whether the covariate is missing
#' ###----------------------------------------------------------------------------###  
gg_forest_covariate_miss <- function(shadow, es_col, se_col, covariate, 
                                     colors = c("#E69F00", "#56B4E9"), 
                                     label = NULL){
  
  # Arrange data for plot
  cov_na <- paste0(covariate, "_NA")
  cov_sym = ensym(covariate) 
  es_sym = ensym(es_col)
  se_sym = ensym(se_col)
  
  tmp = shadow %>% 
    mutate(lb = !!es_sym - 1.96*!!se_sym, # get error bar bounds
           ub = !!es_sym + 1.96*!!se_sym,
           mm = is.na(!!cov_sym)) %>% 
    arrange(desc(mm), # arrange by missingness and 
            !!es_sym,  # effect size
            !!se_sym)  # SE of effect size
  
  
  plot <- ggplot(tmp) + 
    geom_point(aes_string(x = 1:nrow(tmp), y = es_col, color = cov_na)) + 
    geom_segment(aes_string(x = 1:nrow(tmp), xend = 1:nrow(tmp), 
                            y = "lb", yend = "ub", color = cov_na)) + 
    coord_flip() + 
    scale_color_manual(label, 
                       values = colors,
                       labels = c("Observed", "Missing")) + 
  labs(x = "", y = "Effect Size") + 
  theme_bw() +
  theme(axis.text.y = element_blank(), 
        axis.ticks.y = element_blank())
  
  return(plot)
    
}

# gg_forest_covariate_miss(adt_shadow %>% sample_frac(.5),
#                           es_col = "es_g",
#                           se_col = "se_g",
#                           covariate = "g1hrsperweek",
#                           label = "Group 1 Hrs \nPer Week")



mis_ma_var_summary <- function(data, se_col, truncate = TRUE){
  
  n_miss_fun <- function(x){ return(sum(is.na(x))) }
  pct_miss_fun <- function(x){ return(mean(is.na(x)) * 100) }
  wt_miss_fun <- function(x, wt){ return(sum(as.integer(is.na(x)) * wt)/sum(wt) * 100) }
  
  se_vals <- data %>% select(all_of(se_col)) %>% as_vector()
  
  ntab <- data %>% 
    summarize_all(n_miss_fun)
  pctab <- data %>% 
    summarize_all(pct_miss_fun)
  
  sums <- bind_rows(ntab, pctab)
  
  if(!is.null(se_col)){
    
    wpctab <- data %>% 
      summarize_all(.funs = function(x) wt_miss_fun(x, (1/se_vals)^2))
    
    sums <- bind_rows(sums, wpctab)
    row.names(sums) <- c("n_miss", "pct_miss", "wtpct_miss")
    
  } else {
    
    row.names(sums) <- c("n_miss", "pct_miss")
    
  }
  
  sums_tab <- as_tibble(cbind(Variable = names(sums), t(sums))) %>%
    mutate_at(grep("miss", names(.), value = T), as.numeric) %>%
    arrange(desc(n_miss)) 
  
  if(truncate){ sums_tab <- filter(sums_tab, n_miss > 0) }
  
  return(sums_tab)
}

# mis_ma_var_summary(adt_data, "se_g", truncate = FALSE)
